list_display:
    pattern:  /list
    defaults: { _controller: formMakerBundle:List:display }

edit_create:
    pattern:  /edit
    defaults: { _controller: formMakerBundle:Edit:edit }

answers:
    pattern:  /answers/(offset)/{offset}/(form_id)/{formId}
    defaults: { _controller: formMakerBudnle:Answers:display, offset: 0, formId: null }

answers_clean:
    pattern:  /answers
    defaults: { _controller: formMakerBudnle:Answers:display }

remove:
    pattern: /remove/{formId}
    defaults: { _controller: FormMakerBundle:Remove:remove }

default_test:
    pattern:  /test
    defaults: { _controller: formMakerBundle:Default:testAdmin }
