list_display:
    pattern:  /list
    defaults: { _controller: formMakerBundle:List:display }

edit:
    pattern:  /edit/{id}
    defaults: { _controller: formMakerBundle:Edit:edit }

edit_create:
    pattern:  /edit
    defaults: { _controller: formMakerBundle:Edit:edit }

answers:
    pattern:  /answers/(offset)/{offset}/(form_id)/{formId}
    defaults: { _controller: formMakerBudnle:Answers:list, offset: 0, formId: null }

answers_clean:
    pattern:  /answers
    defaults: { _controller: formMakerBudnle:Answers:list }

answer:
    pattern:  /answer/{answerId}
    defaults: { _controller: FormMakerBundle:Answers:details }

remove:
    pattern: /remove/{formId}
    defaults: { _controller: FormMakerBundle:Remove:remove }

default_test:
    pattern:  /test
    defaults: { _controller: formMakerBundle:Default:testAdmin }

render_form:
    pattern: /renderForm/{locationId}/{direction}
    defaults: { _controller: FormMakerBundle:Ajax:renderForm }
    requirements:
        direction: next|prev